services:
    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Товары, manager_type: orm, label: Товары }
        public: true

    admin.stake_offering:
        class: App\Admin\StakeOfferingAdmin
        arguments: [~, App\Entity\StakeOffering, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Ставки, manager_type: orm, label: Ставки }
        public: true

    admin.simple_user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, group: Пользователи, manager_type: orm, label: Пользователи }
        public: true