services:
    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Товары, manager_type: orm, label: Товары }
        public: true

    admin.won_product:
        class: App\Admin\WonProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, group: Товары, manager_type: orm, label: Выигранные аукционы }
        public: true

    admin.stake_offering:
        class: App\Admin\StakeOfferingAdmin
        arguments: [~, App\Entity\StakeOffering, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Ставки, manager_type: orm, label: Ставки }
        public: true

    admin.simple_user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, group: Пользователи, manager_type: orm, label: Пользователи }
        public: true

    admin.support_question:
        class: App\Admin\SupportQuestionAdmin
        arguments: [~, App\Entity\SupportQuestion, ~]
        tags:
            - { name: sonata.admin, group: Пользователи, manager_type: orm, label: Вопросы }
        public: true

    admin.general.about_us:
        class: App\Admin\AboutUsPageAdmin
        arguments: [~, App\Entity\AboutUsPage, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: О нас }
        public: true

    admin.general.main_page:
        class: App\Admin\MainPageAdmin
        arguments: [~, App\Entity\MainPage, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Главная страница }
        public: true

    admin.general.delivery_page:
        class: App\Admin\DeliveryPageAdmin
        arguments: [~, App\Entity\DeliveryPage, ~]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Доставка }
        public: true

    admin.general.faq:
        class: App\Admin\FAQAdmin
        arguments: [~, App\Entity\FAQ, ~]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Вопросы и ответы }
        public: true

    admin.general.bonus_page:
        class: App\Admin\BonusPageAdmin
        arguments: [~, App\Entity\BonusPage, ~, "@app.file_upload"]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Бонусы }
        public: true