sonata_admin:
    title: 'Панель администратора'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
        handler: sonata.admin.security.handler.role

        role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
