sonata_admin:
    title: 'Панель администратора'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            -
              position: right
              type: sonata.block.service.text
              settings:
                  template: admin/user_block.html.twig

    security:
        handler: sonata.admin.security.handler.role

        role_super_admin: ROLE_SUPER_ADMIN

    assets:
        extra_stylesheets:
            - build/css/admin/admin.css


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:
            contexts: [admin]
