#swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }

swiftmailer:
#    disable_delivery: false
    url: 'gmail://bykovski.free@gmail.com:15397715@localhost?encryption=tls&auth_mode=oauth'
    spool: { type: memory }
    sender_address: "bykovski.free@gmail.com"
