index:
    path: /
    controller: App\Controller\MainController::mainPageAction

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix:   /_error